on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    # checkout the repo testd
    - uses: actions/checkout@master

    - run: |
        cat ./Application/test.json
        cat ./Application/test1.yaml
        cat ./Application/SampleWebApplication/Web.config

    - uses: ./variableSubstitution
      with:
        files: 'Application/*.json, Application/*.yaml, Application/**/*.config'
      env:
        auth.key1: "values1"
        auth.key2: "values2"
        DefaultConnection: "Data Source=(ProdDB)\MSSQLProdDB;AttachFileName=Local.mdf"
        auth.key3.subkey1: "hi"
        AdminUserName: "ProdAdminName"
        AdminPassword: "mypassword"

    - run: |
        cat ./Application/test.json
        cat ./Application/test1.yaml
        cat ./Application/SampleWebApplication/Web.config